services:
  app:
    image: "ekamekas/promtail-demo-app:sev_1"
    volumes:
      - "log-data:/var/log"
    ports:
      - "8080:8080"
    networks:
      - front-tier
      - back-tier
  log-collector:
    image: "grafana/promtail"
    volumes:
      - "log-data:/var/log"
      - "./promtail-config.yaml:/etc/promtail/promtail-config.yaml"
    networks:
      - back-tier
    command: -config.file=/etc/promtail/promtail-config.yaml
    depends_on:
      - log-aggregator
  log-aggregator:
    image: "grafana/loki"
    volumes:
      - "./loki-config.yaml:/etc/loki/loki-config.yaml"
    networks:
      - back-tier
    command: -config.file=/etc/loki/loki-config.yaml
  monitoring:
    image: "grafana/grafana-oss"
    volumes:
      - "./grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml"
      - "./grafana-alerting.yaml:/etc/grafana/provisioning/alerting/alerting.yaml"
      - "./grafana-dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml"
      - "./grafana-user_service_dashboard.json:/etc/dashboards/user/user-service_dashboard.json"
    ports:
      - "3000:3000"
    networks:
      - front-tier
      - back-tier

networks:
  front-tier: {}
  back-tier: {}

volumes:
  log-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /var/log
