server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://log-aggregator:3100/loki/api/v1/push

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: applog
      __path__: /var/log/app.log
  pipeline_stages:
  - logfmt:
      mapping:
        timestamp: time
        method:
        path:
        status:
        elapsed:
  - timestamp:
      source: timestamp
      format: RFC3339Nano
